name: Cov19 Auto Complete Action
on: 
    schedule:
    - cron:  '59 23 * * *'
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - uses: actions/checkout@v2
      - id: step1
        run: |
            date
            cd BUPTCovFormAutoComplete
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            python3 AutoComplete.py ${{secrets.USERNAME}} ${{secrets.PASSWORD}}



          
    



  
