name: Cov19 Auto Complete Action
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - uses: actions/checkout@v2
      - id: step1
        run: |
            cd BUPTCovFormAutoComplete
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            python3 AutoComplete.py ${{secrets.USERNAME}} ${{secrets.PASSWORD}}



          
    



  
