name: Cov19 Auto Complete Action
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - id: step3
        run: python --version
      - id: step4
        run: ls
      - id: step5
        run : echo ${{ secrets.PASSWORD }}
    



  
